---
{{- if .Values.memcached.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plone.fullname" . }}-memcached
  labels:
    {{- include "plone.labels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
spec:
  type: ClusterIP
  ports:
    - port: 11211
      targetPort: memcached
      protocol: TCP
      name: memcached
  selector:
    {{- include "plone.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
{{- end }}
---
{{- if .Values.memcached.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plone.fullname" . }}-memcached
  labels:
    {{- include "plone.labels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "plone.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: memcached
  template:
    metadata:
      labels:
        {{- include "plone.labels" . | nindent 8 }}
        app.kubernetes.io/component: memcached
    spec:
      containers:
        - name: memcached
          image: "{{ .Values.memcached.image.repository }}:{{ .Values.memcached.image.tag }}"
          {{- with .Values.memcached.arguments }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: memcached
              containerPort: 11211
              protocol: TCP
          {{- with .Values.memcached.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
